services:
  postgres:
    image: postgres:16
    container_name: admin_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: admin_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
