"""Refactored export jobs

Revision ID: 567b259dc563
Revises: bfe60dddf883
Create Date: 2026-02-26 17:47:09.747789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567b259dc563'
down_revision: Union[str, Sequence[str], None] = 'bfe60dddf883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('processing_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'processing_started_at')
    # ### end Alembic commands ###
