"""added request_id in jobs

Revision ID: 5d0e42f120d2
Revises: 4d782cd2167f
Create Date: 2026-03-17 12:19:24.743090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d0e42f120d2'
down_revision: Union[str, Sequence[str], None] = '4d782cd2167f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('request_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_jobs_request_id'), 'jobs', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_request_id'), table_name='jobs')
    op.drop_column('jobs', 'request_id')
    # ### end Alembic commands ###
