"""refactored jobs and users

Revision ID: 6eaea42a5281
Revises: 5d0e42f120d2
Create Date: 2026-03-18 12:36:50.015453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6eaea42a5281'
down_revision: Union[str, Sequence[str], None] = '5d0e42f120d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.UUID(), nullable=False))
    op.alter_column('jobs', 'id',
                    existing_type=sa.UUID(),
                    type_=sa.String(),
                    existing_nullable=True)
    op.alter_column('jobs', 'request_id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('jobs', 'payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_user_id'), 'jobs', ['user_id'], unique=False)
    op.create_foreign_key("fk_jobs_users", 'jobs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_jobs_users", 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_user_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.alter_column('jobs', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.execute("ALTER TABLE jobs ALTER COLUMN request_id TYPE uuid USING request_id::uuid;")
    op.execute("ALTER TABLE jobs ALTER COLUMN id TYPE uuid USING id::uuid;")

    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###
