"""Added attemts and max_attempts column in export_jobs

Revision ID: fe1f93443edf
Revises: 567b259dc563
Create Date: 2026-03-02 12:14:40.195029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1f93443edf'
down_revision: Union[str, Sequence[str], None] = '567b259dc563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('export_jobs', sa.Column('attempts', sa.Integer(), nullable=False))
    op.add_column('export_jobs', sa.Column('max_attempts', sa.Integer(), nullable=False))
    op.add_column('export_jobs', sa.Column('next_run_at', sa.DateTime(), nullable=True))
    op.add_column('export_jobs', sa.Column('last_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_jobs', 'last_error')
    op.drop_column('export_jobs', 'next_run_at')
    op.drop_column('export_jobs', 'max_attempts')
    op.drop_column('export_jobs', 'attempts')
    # ### end Alembic commands ###
