"""Changed user role type

Revision ID: ffdce1c11a24
Revises: 6eaea42a5281
Create Date: 2026-04-10 13:29:57.321316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffdce1c11a24'
down_revision: Union[str, Sequence[str], None] = '6eaea42a5281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE userrole AS ENUM ('ADMIN','STAFF')"
    )
    op.execute("""
        ALTER TABLE users
        ALTER COLUMN role TYPE userrole
        USING role::userrole
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('ADMIN', 'STAFF', name='userrole'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    
    op.execute("DROP TYPE IF EXISTS userrole")
    # ### end Alembic commands ###
